### ISSUE TITLE
Код не компилируется

### ISSUE THREAD

**Issue by finomen** [Arsegg/programming-languages-1#1]
Scanning dependencies of target HOMEWORK_1
[100%] Building CXX object CMakeFiles/HOMEWORK_1.dir/main.cpp.o
/home/finomen/cpp_2014/54/HOMEWORK-1/main.cpp:6:19: fatal error: conio.h: No such file or directory
compilation terminated.
make[2]: **\* [CMakeFiles/HOMEWORK_1.dir/main.cpp.o] Error 1
make[1]: **\* [CMakeFiles/HOMEWORK_1.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Arsegg** [comment]
Удалил импорты.
